# Site settings
title: Rebecca Goldberg Consulting
tagline: Youth Development & Philanthropy Consulting
description: >- # this means to ignore newlines until "baseurl:"
  Independent consultant partnering with foundations and nonprofits on grantmaking
  strategy, funder collaboration, and youth development.
baseurl: "/" # the subpath of your site, e.g. /blog/
url: "https://rebeccagoldberg.org" # the base hostname & protocol for your site (must match CNAME)
author: Rebecca Goldberg
logo: /assets/img/logo3.png
lang: en_US

# Build settings
safe: true # always trues on github-pages, disables _plugins/
markdown: kramdown
sass:
  indentWidth: 4
  style: compressed
  precision: 10
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
exclude:
  - Gemfile
  - Gemfile.lock
  - build-in-docker.sh
  - README.md
